### ISSUE TITLE
set-default is converting bool into int

### ISSUE THREAD

**Issue by RogerThiede** [msanders/cider#28]
When using ```cider set-default -bool```, the given domain key is properly stored into ```defaults.yaml``` but the given domain key is not properly applied to the system.  boolean ```true``` and ```false``` are converted into ```int```.

```
» cider set-default -bool com.apple.desktopservices DSDontWriteNetworkStores TRUE
» defaults read com.apple.desktopservices                                        
{
    DSDontWriteNetworkStores = 1;
}
» cider set-default -bool com.apple.desktopservices DSDontWriteNetworkStores true
» defaults read com.apple.desktopservices
{
    DSDontWriteNetworkStores = 1;
}


» cider set-default com.apple.desktopservices DSDontWriteNetworkStores TRUE
» defaults read com.apple.desktopservices                                  
{
    DSDontWriteNetworkStores = 1;
}
» cider set-default com.apple.desktopservices DSDontWriteNetworkStores true
» defaults read com.apple.desktopservices                                  
{
    DSDontWriteNetworkStores = 1;
}
```

Expected behavior is:
```
» defaults write com.apple.desktopservices DSDontWriteNetworkStores true
» defaults read com.apple.desktopservices                               
{
    DSDontWriteNetworkStores = true;
}
» 
```

**Comment by RogerThiede** [comment]
Actually this might be my misunderstanding with OS X ```defaults write```, but I'd like another opinion on it.

**Comment by msanders** [comment]
I think this may be a quirk with the `defaults` command. You can see the command cider uses if you pass in the `--debug` flag:

```sh
$ cider --debug set-default -bool com.apple.desktopservices DSDontWriteNetworkStores TRUE
==> defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool True
$ defaults read com.apple.desktopservices
{
    DSDontWriteNetworkStores = 1;
}
```

In your last example, it looks like you're setting the value to the string "true", which may or may not do what you want (Objective-C apps often [implicitly convert these values to true](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/index.html#//apple_ref/occ/instp/NSString/boolValue)).

**Comment by RogerThiede** [comment]
That makes sense.  The OS X defaults application is choosing to store
bool's as 0 or 1.  My example in expected behavior was a bad example
because I was actually setting a string (which ends up also having the
desired effect.)

Not a bug.

Thanks.
