### ISSUE TITLE
`brew cask outdated` no longer available

### ISSUE THREAD

**Issue by ratson** [msanders/cider#32]
The lastest version (0.60.0) does not have `brew cask outdated` anymore.

**Comment by RogerThiede** [comment]
`cider restore` depends on `brew cask outdated` and so this is necessary for normal cider functionality.

**Comment by mdomke** [comment]
+1

**Comment by yanfali** [comment]
:+1: is this package now unmaintained?

**Comment by RogerThiede** [comment]
The owner commented on the proposed pull request #33.
