### ISSUE TITLE
Unknown command: uses

### ISSUE THREAD

**Issue by RogerThiede** [msanders/cider#35]
`cider cask missing`

> Error: Unknown command: uses
`Whoops! `brew cask uses --installed --recursive google-chrome` failed with code 1`

Fresh installation of OS X 10.11 with cider 1.1.8.

**Comment by grange74** [comment]
It got same error but for a different program.

```cider cask missing```
> Error: Unknown command: uses
Whoops! `brew cask uses --installed --recursive eclipse-jee` failed with code 1

Same version of cider 1.1.8 and OSX 10.11.6.
```cider missing``` and ```cider tap missing``` worked fine.

**Comment by msanders** [comment]
Fixed by @JMSwag in #37.
