### ISSUE TITLE
Add mas support

### ISSUE THREAD

**Issue by Bartuz** [msanders/cider#36]
Mas is a command line interface for mac App Store. Looks like you could also be able to bootstrap your mac purchases with cider :)

looking forward implementing it

 https://github.com/argon/mas

**Comment by RogerThiede** [comment]
👍  This opens up an entire ecosystem to cider.

**Comment by maxnowack** [comment]
Are there any updates on this?

**Comment by RogerThiede** [comment]
Given that [cider](https://github.com/msanders/cider) is designed for "bootstrapping with Homebrew", and that [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) is both built into [Homebrew](https://brew.sh/) and now includes the capability for installing Mac App Store applications using [mas-cli](https://github.com/argon/mas), this enhancement is arguably moot.

Cider is valuable to me for its features of `symlinks`, `defaults`, and `after-scripts` with among other scripts, a specific after-script of executing `brew bundle` with an accompanying Brewfile.  Said Brewfile includes mas support.

**Comment by msanders** [comment]
This is now supported by Cider's replacement, [`zero.sh`](https://github.com/zero-sh/zero.sh), which includes support for Brewfiles (see #46). Let me know what you think.
