### ISSUE TITLE
cider set-default to handle array values

### ISSUE THREAD

**Issue by RogerThiede** [msanders/cider#51]
Cider storage of defaults and applying defaults doesn't appear to support arrays.

Example usage:
`defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'`

**Comment by RogerThiede** [comment]
My intention is to be able to save new persistent applications into the Dock.
Since my common usage of Cider is when installing new macOS versions which keep changing the default value of `com.apple.dock persistent-apps`, I don't want `cider apply-defaults` to erase the entire `persistent-apps` value.

**Comment by msanders** [comment]
This issue has been migrated to https://github.com/zero-sh/apply-user-defaults/issues/1.
